package com.csk.leetcode.hashtable;

/**
 * Created by 24866 on 2017/5/14.
 *
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class FindTheDifference {

    //自己的想法 还是不够好 可以想到用亦或会更好
    public char findTheDifference(String s, String t) {
        int c = 0;
        for(int i = 0;i < t.length();i++)
            c += t.charAt(i);
        for(int i = 0;i < s.length();i++)
            c -= s.charAt(i);
        return (char)c;
    }

    public char findTheDifference_(String s, String t) {
        int a = 0;
        for(char c:s.toCharArray())
            a ^= c;
        for(char c:t.toCharArray())
            a ^= c;
        return (char)a;
    }
}
